---
driver:
  name: proxy
  host: localhost
  reset_command: 'exit 0'
  port: <%= ENV['MACHINE_PORT'] %>
  username: <%= ENV['MACHINE_USER'] %>
  password: <%= ENV['MACHINE_PASSWORD'] %>

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.12.3

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[capish::default]
      - recipe[capish_repo_test::default]
      - recipe[capish_repo_test::private]
      - recipe[capish_repo_test::no_deploy]
      - recipe[capish_repo_test::unstage]
      - recipe[capish_repo_test::unstage_deployed]
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/capish_repo_default
        - test/integration/capish_repo_private
        - test/integration/capish_repo_no_deploy
        - test/integration/capish_repo_unstage
        - test/integration/capish_repo_unstage_deployed
    attributes:
