name 'capish'
maintainer 'Paul Holden'
maintainer_email 'paul@holdensoftware.com'
license 'ISC'
description 'Simple Capistrano-like code deployment.'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.1.0'
chef_version '>= 13.0'
supports 'ubuntu'
issues_url 'https://github.com/paulholden2/capish/issues'
source_url 'https://github.com/paulholden2/capish'
gem 'git', '~> 1.5.0'
